{% set version = "1.2.0" %}

package:
  name: partd
  version: {{ version }}

source:
  fn: partd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: aa67897b84d522dcbc86a98b942afab8c6aa2f7f677d904a616b74ef5ddbc3eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - locket
    - toolz

  run:
    - python >=3.5
    - locket
    - toolz

test:
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Data structure for on-disk shuffle operations

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
    - jrbourbeau
